branch-defaults:
  default:
    environment: flask-checkin-env
    group_suffix: null
  master:
    environment: checkInWB
environment-defaults:
  checkInWB:
    branch: master
    repository: origin
  flask-checkin-env:
    branch: null
    repository: null
global:
  application_name: Check-In-Web-App
  branch: null
  default_ec2_keyname: DSCS-eb
  default_platform: python2.7
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
